### ISSUE TITLE
Allow for generating a token with NadeoServices audience

### ISSUE THREAD

**Issue by chipsTM** [openplanet-nl/nadeoservices#1]
As some in game apis are not exposed/available, but are exposed on the [Core API](https://github.com/openplanet-nl/core-api-tracking) it would be nice to be able to generate a Token that can connect to various https://prod.trackmania.core.nadeo.online/ endpoints

**Comment by ezio416** [comment]
I think specifically this needs to be done in [CGameManiaPlanetScriptAPI](https://next.openplanet.dev/Game/CGameManiaPlanetScriptAPI), as `Authentication_GetToken()` with the "NadeoServices" audience sets `Authentication_ErrorCode` to 12

**Comment by codecat** [comment]
This must be done externally (through reverse engineering). The work for this is already done, I just need to add it to the API.
